### ISSUE TITLE
Why inconsistent returning types?

### ISSUE THREAD

**Issue by Mec-iS** [jgraef/python3-ipfs-api#5]
Is there any explanation for `object.data()` returning a `HTTPResponse` object and instead `object.links()` returning a dictionary?
Probably `data()` should return `bytes`?

**Comment by jgraef** [comment]
Methods that work on raw data use file-like objects (`HTTPResponse` acts as a file-like object) for input and output.

**Comment by Mec-iS** [comment]
ok, I add that to `data()` docstring.
